#!/usr/bin/env node
// Creates the draft folder for one article and moves the fetched video material into it.
//
// Usage:
//   node init-draft.mjs <slug> --video <primary-url> [--video <extra-url> ...] [--author Muthu] [--keyword "..."] [--audience "..."]
//
// Creates content/drafts/<slug>/ with:
//   article.md, metadata.json (status RESEARCHING), research.md, sources.md, quality-audit.md,
//   screenshots/, _source/ (video.json + transcript, moved from content/drafts/.inbox/<videoId>/)
// Also makes sure content/ideas/backlog.md and content/.gitignore exist.
// Refuses to touch a folder that already exists.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DRAFTS_DIR, videoId } from './lib/library-core.mjs';

const TEMPLATES = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'templates');
const CONTENT_DIR = path.dirname(DRAFTS_DIR);

function opt(args, name, dflt = '') {
  const i = args.indexOf(name);
  return i === -1 ? dflt : args[i + 1];
}
function fmtLen(sec) {
  if (!sec) return 'unknown length';
  const m = Math.floor(sec / 60), s = sec % 60;
  return `${m}:${String(s).padStart(2, '0')}`;
}

const args = process.argv.slice(2);
const slug = args[0];
// --video can repeat: the first is the primary source video, the rest are extra research videos.
const videoUrls = args.flatMap((a, i) => (a === '--video' && args[i + 1] ? [args[i + 1]] : []));
const videoUrl = videoUrls[0];
const author = opt(args, '--author', 'Muthu');
const keyword = opt(args, '--keyword');
const audience = opt(args, '--audience');

if (!slug || !videoUrl) {
  console.error('Usage: node init-draft.mjs <slug> --video <youtube-url> [--author Muthu] [--keyword "..."] [--audience "..."]');
  process.exit(1);
}
if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug) || slug.length > 75) {
  console.error(`Bad slug "${slug}": lowercase kebab-case, max 75 chars`);
  process.exit(1);
}
const vid = videoId(videoUrl);
if (!vid) { console.error(`Not a YouTube URL: ${videoUrl}`); process.exit(1); }

const dir = path.join(DRAFTS_DIR, slug);
if (fs.existsSync(dir)) {
  console.error(`${dir} already exists. Update that draft instead, or choose a different slug.`);
  process.exit(1);
}
fs.mkdirSync(path.join(dir, 'screenshots'), { recursive: true });
fs.mkdirSync(path.join(dir, '_source'), { recursive: true });

const inbox = path.join(DRAFTS_DIR, '.inbox', vid);
if (fs.existsSync(inbox)) {
  for (const f of fs.readdirSync(inbox)) fs.renameSync(path.join(inbox, f), path.join(dir, '_source', f));
  fs.rmdirSync(inbox);
}
// Extra research videos live in _source/<videoId>/; audit-draft.mjs checks overlap against all of them.
const extraVideos = [];
for (const u of videoUrls.slice(1)) {
  const id = videoId(u);
  if (!id) { console.error(`Skipping non-YouTube URL: ${u}`); continue; }
  const src = path.join(DRAFTS_DIR, '.inbox', id);
  const dest = path.join(dir, '_source', id);
  if (fs.existsSync(src)) fs.renameSync(src, dest);
  const vj = path.join(dest, 'video.json');
  const v = fs.existsSync(vj) ? JSON.parse(fs.readFileSync(vj, 'utf8')) : {};
  extraVideos.push({ url: `https://www.youtube.com/watch?v=${id}`, title: v.title || '', channel: v.channel || '', hasTranscript: fs.existsSync(path.join(dest, 'transcript.json')) });
}

const videoPath = path.join(dir, '_source', 'video.json');
const video = fs.existsSync(videoPath) ? JSON.parse(fs.readFileSync(videoPath, 'utf8')) : {};
const transcriptPath = path.join(dir, '_source', 'transcript.json');
const transcript = fs.existsSync(transcriptPath) ? JSON.parse(fs.readFileSync(transcriptPath, 'utf8')) : null;
const today = new Date().toISOString().slice(0, 10);
const canonicalVideo = `https://www.youtube.com/watch?v=${vid}`;

const vars = {
  WORKING_TITLE: video.title || slug,
  VIDEO_TITLE: video.title || '(title unknown)',
  VIDEO_URL: canonicalVideo,
  CHANNEL: video.channel || '(channel unknown)',
  LENGTH: fmtLen(video.lengthSeconds),
  PUBLISH_DATE: (video.publishDate || 'unknown').slice(0, 10),
  TRANSCRIPT_NOTE: transcript
    ? `${transcript.language}${transcript.isAutoGenerated ? ', auto-generated captions: expect errors in names and numbers' : ', creator-provided captions'}, via ${transcript.method}`
    : 'NOT YET RETRIEVED',
  TODAY: today,
};
const fill = s => s.replace(/\{\{(\w+)\}\}/g, (m, k) => (k in vars ? vars[k] : m));

for (const f of ['article.md', 'research.md', 'sources.md', 'quality-audit.md']) {
  // {{H1}} is left unfilled on purpose: it's decided after research, and the audit fails on leftover placeholders.
  fs.writeFileSync(path.join(dir, f), fill(fs.readFileSync(path.join(TEMPLATES, f), 'utf8')));
}

const meta = JSON.parse(fs.readFileSync(path.join(TEMPLATES, 'metadata.json'), 'utf8'));
Object.assign(meta, {
  slug,
  primaryKeyword: keyword,
  targetAudience: audience,
  sourceVideo: canonicalVideo,
  sourceVideoTitle: video.title || '',
  sourceChannel: video.channel || '',
  additionalVideos: extraVideos,
  author,
  status: 'RESEARCHING',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});
fs.writeFileSync(path.join(dir, 'metadata.json'), JSON.stringify(meta, null, 2) + '\n');

// Transcripts are someone else's words and only a research input, so keep them out of git.
const gitignore = path.join(CONTENT_DIR, '.gitignore');
if (!fs.existsSync(gitignore)) {
  fs.writeFileSync(gitignore, '# Source transcripts are research inputs, not our content\ndrafts/.inbox/\ndrafts/*/_source/\n');
}
const backlog = path.join(CONTENT_DIR, 'ideas', 'backlog.md');
if (!fs.existsSync(backlog)) {
  fs.mkdirSync(path.dirname(backlog), { recursive: true });
  fs.writeFileSync(backlog, '# Content ideas backlog\n\nIdeas spotted while researching other articles. Not drafted yet. Run `library.mjs check` before starting one.\n\n'
    + '| Idea (working title) | Primary keyword | Search intent | Why it is worth a separate article | Found while researching | Added | Status |\n'
    + '|---|---|---|---|---|---|---|\n');
}

console.log(`Created ${path.relative(process.cwd(), dir)}`);
console.log(transcript ? `Transcript moved into _source/ (${transcript.segments.length} segments)` : 'No transcript in _source/ yet — add _source/transcript.txt before drafting (see SKILL.md step 2 fallbacks)');
